theme: jekyll-theme-minimal
title: Hacktoberfest Mauritius
logo: https://github.com/arwinneil/hacktoberfest-mauritius/raw/master/assets/hacktoberfest_logo.png
description: Hacktoberfest is an annual month-long event held in the month of October organised by GitHub and Digital Ocean. This is a month to celebrate and encourage developers to get involved and contribute to open source projects.
